### ISSUE TITLE
Verification Failed

### ISSUE THREAD

**Issue by vkaschandra** [shekharAggarwal/CarYatri#1]
Hello Shekar , I appreciate your efforts . The issue is , when I try to create an account its prompting verification failed .

**Comment by shekharAggarwal** [comment]
on which screen.

**Comment by vkaschandra** [comment]
on login screen.. do I have to install XAMP?

**Comment by shekharAggarwal** [comment]
its working fine for me.
did you created a account.

**Comment by shekharAggarwal** [comment]
[back-end code link](https://github.com/shekharAggarwal/gag-backend)
[Driver app](https://github.com/shekharAggarwal/URDriver)

In firebase you have configure it.
and then open phone Auth and Realtime database in firebase project.

This is text file convert it into json file and upload in firebase database [realtime_database.txt](https://github.com/shekharAggarwal/CarYatri/files/8148548/realtime_database.txt)

**Comment by vkaschandra** [comment]
Thank you
    On Sunday, 27 February, 2022, 04:54:17 pm IST, Shekhar Aggarwal ***@***.***> wrote:  
 
 


Closed #1.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
